# Generated by Django 5.0.7 on 2024-08-05 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calcium', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('carbohydrate', models.FloatField(default=0)),
                ('cholesterol', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('monounsaturated_fat', models.FloatField(default=0)),
                ('polyunsaturated_fat', models.FloatField(default=0)),
                ('potassium', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('saturated_fat', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('vitamin_a', models.FloatField(default=0)),
                ('vitamin_c', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
