# Generated by Django 5.0.7 on 2024-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.FloatField(default=0)),
                ('food_name', models.CharField(max_length=200)),
            ],
        ),
    ]
