# Generated by Django 5.0.7 on 2024-08-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0002_calorietracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalorieTracker',
        ),
    ]
