# Generated by Django 5.0.7 on 2024-08-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0008_userhealthdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHealthData',
        ),
    ]
