# Generated by Django 5.0.7 on 2024-08-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0010_userhealthdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHealthData',
        ),
    ]
