# Generated by Django 5.0.7 on 2024-09-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0013_caloriegoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalorieGoal',
        ),
    ]
